---
- name: pull artifacts from jenkins"
  hosts: "{{ubuntu-server}}"
#  user: "{{user}}"
  tasks:   
    - name: Copy the file from jenkins to ubunut
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{dest_deploy}}"
        mode: pull
      delegate_to: "{{jenkins-server}}"
      register: syncfile
      run_once: true
      with_items:
       - "{{src_jenkins}}"
